# Generated by Django 5.0.3 on 2024-09-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='contene',
            new_name='content',
        ),
    ]
