# Generated by Django 5.0.3 on 2024-09-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_author_alter_blog_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default=465, upload_to='', verbose_name='图片'),
            preserve_default=False,
        ),
    ]
